CREATE DATABASE CulinaryBookDB;
GO
USE CulinaryBookDB;
GO
CREATE TABLE Authors (
    AuthorID INT IDENTITY PRIMARY KEY,
    AuthorName NVARCHAR(150) NOT NULL,
    Login NVARCHAR(100) NOT NULL UNIQUE,
    Password NVARCHAR(100) NOT NULL,
    BirthDay DATE NULL,
    Stage FLOAT NULL,
    Mail NVARCHAR(100) NULL,
    Number NVARCHAR(30) NULL
);
CREATE TABLE Categories (CategoryID INT IDENTITY PRIMARY KEY, CategoryName NVARCHAR(100) NOT NULL);
CREATE TABLE Recipes (
    RecipeID INT IDENTITY PRIMARY KEY,
    RecipeName NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    CategoryID INT NULL FOREIGN KEY REFERENCES Categories(CategoryID),
    AuthorID INT NULL FOREIGN KEY REFERENCES Authors(AuthorID),
    CookingTime INT NULL,
    Image NVARCHAR(50) NULL
);
CREATE TABLE RecipeImages (ImageID INT IDENTITY PRIMARY KEY, RecipeID INT NOT NULL FOREIGN KEY REFERENCES Recipes(RecipeID) ON DELETE CASCADE, ImagePath NVARCHAR(255) NOT NULL);
CREATE TABLE CookingSteps (StepID INT IDENTITY PRIMARY KEY, RecipeID INT NOT NULL FOREIGN KEY REFERENCES Recipes(RecipeID) ON DELETE CASCADE, StepNumber INT NOT NULL, StepDescription NVARCHAR(MAX) NOT NULL);
CREATE TABLE LikeRecipes (id INT IDENTITY PRIMARY KEY, idAuthor INT NOT NULL FOREIGN KEY REFERENCES Authors(AuthorID) ON DELETE CASCADE, idRecipes INT NOT NULL FOREIGN KEY REFERENCES Recipes(RecipeID) ON DELETE CASCADE);
CREATE TABLE Ingredients (IngredientID INT IDENTITY PRIMARY KEY, IngredientName NVARCHAR(150) NOT NULL);
CREATE TABLE RecipeIngredients (RecipeIngredientID INT IDENTITY PRIMARY KEY, RecipeID INT NOT NULL FOREIGN KEY REFERENCES Recipes(RecipeID) ON DELETE CASCADE, IngredientID INT NOT NULL FOREIGN KEY REFERENCES Ingredients(IngredientID), Quantity NVARCHAR(50) NULL);
